name: CI

on:
  workflow_dispatch:  # 手动触发事件

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install boost-test boost-format boost-filesystem cimg libpng libplist libjpeg-turbo pybind11 utfcpp
          cd ../
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build ./
      - name: Upload binaries as artifact
        run: |
          cd build
          # Assuming the binary is in build/ folder, adjust this path accordingly
          zip -r binary.zip *
        # Upload the binary.zip as an artifact
        - uses: actions/upload-artifact@v2
          with:
            name: binary
            path: build/binary.zip

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: binary
          path: ./binary

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Adjust this tag according to your needs
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./binary/binary.zip
          asset_name: binary.zip
          asset_content_type: application/zip
