name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install boost-format
          ./vcpkg install boost-filesystem
          ./vcpkg install cimg
          ./vcpkg install libpng 
          ./vcpkg install libplist
          ./vcpkg install libjpeg-turbo
          cd ../
          
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build . 

      - name: Setup archive
        shell: bash
        run: |
          7z a -tzip windows-latest.zip build/

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: windows-latest.zip
