name: CI

on:
  workflow_dispatch:  # 手动触发事件

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # 正确使用 GitHub 提供的 vcpkg action
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # 这里填写需要安装的包
          packages: boost-test boost-format boost-filesystem cimg libpng libplist libjpeg-turbo pybind11 utfcpp
          # vcpkgVersion: '2023.08.15' # 你可以指定一个特定版本，也可以省略此行使用最新版本
          
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build ./ 

      - name: Setup archive
        shell: bash
        run: |
          cd ../
          7z a "windows-latest.zip" "build"

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: "windows-latest.zip"
          draft: true  # 创建一个草稿版本的 Release
          release_name: "Latest Windows Build"
