name: CI

on:
  workflow_dispatch:  # 手动触发事件

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # 正确使用 GitHub 提供的 vcpkg action
      - name: Set up vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install boost-test
          ./vcpkg install boost-format
          ./vcpkg install boost-filesystem
          ./vcpkg install cimg
          ./vcpkg install libpng 
          ./vcpkg install libplist
          ./vcpkg install libjpeg-turbo
          cd ../
          
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build ./ 

      - name: Setup archive
        shell: bash
        run: |
          cd ../
          7z a "windows-latest.zip" "build"

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: "windows-latest.zip"
          draft: true  # 创建一个草稿版本的 Release
          release_name: "Latest Windows Build"
