name: CI

on:
  workflow_dispatch:  # 手动触发事件

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install boost-test boost-format boost-filesystem cimg libpng libplist libjpeg-turbo pybind11 utfcpp
          cd ../
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build ./

      - name: Setup archive
        shell: bash
        run: |
          cd ../
          7z a "windows-latest.zip" "build"

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: "windows-latest.zip"
          draft: true  # 创建一个草稿版本的 Release
          release_name: "Latest Windows Build"
