name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install boost-format
          ./vcpkg install boost-filesystem
          ./vcpkg install cimg
          ./vcpkg install libpng 
          ./vcpkg install libplist
          ./vcpkg install libjpeg-turbo
          cd ../
          
      - name: Configure project (Release mode)
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release ..

      - name: Build project
        run: |
          cd build
          cmake --build . --config Release

      - name: Print current directory (cmd)
        run: |
          echo Current Path: %cd%
        shell: cmd

      - name: Setup archive
        shell: bash
        run: |
          7z a texturepacker.zip build

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: texturepacker.zip
